"""test

Revision ID: 509e2ec27745
Revises: 9303df39da00
Create Date: 2019-12-16 14:13:31.731944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509e2ec27745'
down_revision = '9303df39da00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
